# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_value', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='visobjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_pic', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr', to='objects.visobjects'),
        ),
    ]
